### ISSUE TITLE
How is energy consumption is calculated?

### ISSUE THREAD

**Issue by veysiadn** [SiliconLabs/mltk#2]
Hello, I use MLTK library for profiling my tflite model and so far it has been really useful for me. I was wondering about the calculation of energy per inference metric.
In the documentation (https://siliconlabs.github.io/mltk/docs/guides/model_profiler.html), it says that,
"Estimates required energy per inference
NOTE: Estimates are provided based on the ARM Cortex-M33."

I understand that estimations are based on Cortex-M33, but it is not clear to me how is it calculated. 
Is there any specific formula for the calculation?

**Comment by sldriedler** [comment]
Hi, thank you for your feedback.

The energy is estimated using "traditional" machine learning:
https://github.com/SiliconLabs/mltk/blob/master/mltk/core/tflite_micro/accelerators/mvp/estimator/base_estimator.py#L123

For each layer in the model, the various parameters are extracted/calculated and then provided as in input a an energy prediction ML model.
The ML model then generates a "prediction" on the amount of energy that layer would require for the given parameters.
All of the layers' predictions are then summed together to get the total estimated energy required by the model.

Hope this helps.

**Comment by veysiadn** [comment]
Thank you for your quick response. 
Is there any reference for this "traditional" machine learning model for the estimation?
I'm curious about how accurate these estimations are.

**Comment by sldriedler** [comment]
The energy estimating models are "experimental" and the details for them are not published.
They work best with the CNNs, especially standard model architectures such as MobileNet and ResNet.
We were seeing accuracies between 5-20%.

**Comment by veysiadn** [comment]
I understand, thanks again. I guess the estimation accuracy is too low for me to use it as reference.
I think this issue can be closed then.
